### ISSUE TITLE
Meta Keyword and Description not rendered in attribute landings page frontend 

### ISSUE THREAD

**Issue by maxserv-woostelbos** [EmicoEcommerce/Magento2AttributeLanding#19]
Hi Edwin, 

We have installed "Magento2AttributeLanding" on 2 of our platforms. Everything is working as expected except for 2 things (in both shops):
- The meta keywords are not rendered in the source
- The meta description is not rendered in the source

I've already took a look in the file that should handle the logic: 
vendor/emico/m2-attributelanding/src/Observer/SeoObserver.php

The execute message is triggered and for example "$page->getMetaDescription()" isset correctly. But '$this->pageConfig->setDescription()' does not end up adding this data.

I've already tried this with basic magento modules in luma aswell. There is nothing usefull in logging files. 

Can you take a look if you encounter the same problem? In a demo store for example?

Magento and tweakwise versions:

- magento/product-community-edition: 2.3.5-p2
- emico/tweakwise: v3.2.0
- emico/tweakwise-export: v2.1.0
- emico/m2-attributelanding: v1.1.4
- emico/m2-attributelanding-tweakwise: v2.1.0

Thanks in advance.

**Comment by edwinljacobs** [comment]
Hi,

I don't seem to have this issue. Here are the associated traces
```
==== In vendor/emico/m2-attributelanding/src/Observer/SeoObserver.php
#0 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Emico\AttributeLanding\Observer\SeoObserver->execute(Object(Magento\Framework\Event\Observer))
#1 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Emico\AttributeLanding\Observer\SeoObserver), Object(Magento\Framework\Event\Observer))
#2 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#3 /var/www/tweakwise2-ce-seo.test/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('core_layout_blo...', Array)
#4 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Layout/Generator/Block.php(150): Magento\Framework\Event\Manager\Proxy->dispatch('core_layout_blo...', Array)
#5 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Layout/GeneratorPool.php(81): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#6 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Layout.php(350): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#7 /var/www/tweakwise2-ce-seo.test/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#8 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#9 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#10 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#11 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Page/Config.php(224): Magento\Framework\View\Layout\Builder->build()
#12 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Page/Config.php(237): Magento\Framework\View\Page\Config->build()
#13 /var/www/tweakwise2-ce-seo.test/generated/code/Magento/Framework/View/Page/Config/Interceptor.php(37): Magento\Framework\View\Page\Config->publicBuild()
#14 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Result/Page.php(242): Magento\Framework\View\Page\Config\Interceptor->publicBuild()
#15 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#16 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#17 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#18 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#19 /var/www/tweakwise2-ce-seo.test/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#20 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#21 /var/www/tweakwise2-ce-seo.test/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#22 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http\Interceptor->launch()
#23 /var/www/tweakwise2-ce-seo.test/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#24 {main}

==== In vendor/magento/framework/View/Page/Config/Renderer.php
#0 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Page/Config/Renderer.php(134): Magento\Framework\View\Page\Config\Renderer->renderMetadata()
#1 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Result/Page.php(250): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#2 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#3 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#4 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#5 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#6 /var/www/tweakwise2-ce-seo.test/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(130): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#7 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#8 /var/www/tweakwise2-ce-seo.test/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()
#9 /var/www/tweakwise2-ce-seo.test/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http\Interceptor->launch()
#10 /var/www/tweakwise2-ce-seo.test/pub/index.php(40): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#11 {main}
```

In vendor/magento/framework/View/Page/Config/Renderer.php 
Method renderMetadata line 157) should render the metadata
```php
/**
     * Render metadata
     *
     * @return string
     */
    public function renderMetadata()
    {
        $result = '';
        foreach ($this->pageConfig->getMetadata() as $name => $content) {
            $metadataTemplate = $this->getMetadataTemplate($name);
            if (!$metadataTemplate) {
                continue;
            }
            $content = $this->processMetadataContent($name, $content);
            if ($content) {
                $result .= str_replace(['%name', '%content'], [$name, $content], $metadataTemplate);
            }
        }

        return $result;
    }
```

Here ```$this->pageConfig``` is an instance of \Magento\Framework\View\Page\Config (The same one as passed in the SeoObserver). The renderer is an instance of \Magento\Framework\View\Page\Config\RendererInterface, perhaps you have a different implementation for that interface?

I am currently on M2.3.4 on my sample environment with the latest versions of all modules installed (there could be a mismatch there). I checked on one of my demo environments and got

```html
<meta charset="utf-8"/>
<meta name="title" content="blauwe producten"/>
<meta name="description" content="de beste blauwe producten"/>
<meta name="keywords" content="blauw | producten"/>
<meta name="robots" content="INDEX,FOLLOW"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta name="format-detection" content="telephone=no"/>
```

This matches my settings for that page
![demo-blue-products](https://user-images.githubusercontent.com/11278380/102888546-4f692100-4459-11eb-8062-54057c27706c.png)

I hope this helps, With kind regards

**Comment by maxserv-woostelbos** [comment]
He Edwin,

Thanks for the clarification. I already found a plugin that's responsible for the bug :-). 

Sorry for the hassle.

**Comment by edwinljacobs** [comment]
Ok nice to hear! Closing this issue.

With kind regards
