### ISSUE TITLE
TypeError: get_parent_class(): Argument #1 ($object_or_class)

### ISSUE THREAD

**Issue by Kiwifu** [EmicoEcommerce/Magento2AttributeLanding#77]
TypeError: get_parent_class(): Argument #1 ($object_or_class) must be an object or a valid class name, string given in /vendor/magento/framework/Code/Reader/ClassReader.php:98

**Comment by ah-net** [comment]
@Kiwifu Do you have more information on how to reproduce the issue?

**Comment by ah-net** [comment]
Closed due to inactivity

**Comment by rikwillems** [comment]
@ah-net I'm running into what appears to be similar. This happens when creating a new page in "Landing page management".  The file `src/view/adminhtml/ui_component/emico_attributelanding_page_form.xml` references a Tweakwise class two times. This causes this issue. I don't think the Tweakwise class should be referenced here.

```
TypeError: get_parent_class(): Argument #1 ($object_or_class) must be an object or a valid class name, string given in vendor/magento/framework/Code/Reader/ClassReader.php:98
Stack trace:
#0 vendor/magento/framework/Code/Reader/ClassReader.php(98): get_parent_class('Tweakwise\\Magen...')
#1 vendor/magento/framework/View/Element/UiComponent/Argument/Interpreter/ConfigurableObject.php(142): Magento\Framework\Code\Reader\ClassReader->getParents('Tweakwise\\Magen...')
```
